Time: 2023-07-11 00:47:01
Exception: HTTPConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /send_msg?message_type=message&group_id=709743734&message=BLG_whzy%E4%B8%8B%E6%92%AD%E4%BA%86...%0A%E7%9C%8B%E4%BC%9A%E6%AF%94%E8%B5%9BTYLOO-ASE%0A%E7%9B%B4%E6%92%AD%E5%88%86%E5%8C%BA%EF%BC%9A%E7%BD%91%E7%BB%9C%E6%B8%B8%E6%88%8F-%E7%BD%91%E6%B8%B8-%E6%97%A0%E7%95%8F%E5%A5%91%E7%BA%A6%0A%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%0A%5BCQ%3Aimage%2Cfile%3Dhttps%3A%2F%2Fi0.hdslb.com%2Fbfs%2Flive%2Fnew_room_cover%2Fc18e7ee4d87285a5dc94a2067b025aeabab4ae9e.jpg%5D%0Ahttps%3A%2F%2Flive.bilibili.com%2F25277646 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa2ab3656d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Line: 112